### ISSUE TITLE
Error when navigating to Manage Tweak Packages

### ISSUE THREAD

**Issue by JRBrownNKU** [Tweaks/Tweaks#1]
The following error is generated when I attempt to browse to Building Blocks > Installed Tools > Settings > Manage Tweak Packages.

Error
                \usr\local\blackboard\content\vi\bb_bb60\plugins\qut-tweakbb\webapp\admin\tweak_packages.xml (The system cannot find the path specified)

java.io.FileNotFoundException: \usr\local\blackboard\content\vi\bb_bb60\plugins\qut-tweakbb\webapp\admin\tweak_packages.xml (The system cannot find the path specified)
                at java.io.FileInputStream.open(Native Method)
                at java.io.FileInputStream.(FileInputStream.java:106)
                at java.io.FileInputStream.(FileInputStream.java:66)
                at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:70)
                at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:161)
                at org.apache.xerces.impl.XMLEntityManager.setupCurrentEntity(Unknown Source)
                at org.apache.xerces.impl.XMLVersionDetector.determineDocVersion(Unknown Source)
                at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
                ….

It appears it is attempting to reference an absolute UNIX path.  Since we are Windows environment, this path is not valid.  Is there a version of the building block compatible with Windows environments?

**Comment by Tweaks** [comment]
Thanks heaps for picking this up. I found the absolute paths. Will fix, rebuild and test in next day or so -- our servers are in disaster recovery mode at the moment. Not sure if I have access to a Windows box running BB to test.. I"ll ask my sys admin when people get back

**Comment by JRBrownNKU** [comment]
Thanks.  Probably be good to have it use shared dir as specified in bb-config to accomodate load-balanced installs.

Should I look on Oscelot for updated version in a few days?

**Comment by Tweaks** [comment]
Removed absolute paths Fixed and tested in 3.1.5. Thanks heaps!
